fix: message presend process not working
jsxc/jsxc pull request #1018
Opened 2021-02-24 08:51 UTC by anvyzhang

Problem is

* When I process a message in presend functions, like do some string replacement on message content.
* Send the message out, sender's message area shows a new message without those string replacement .
* But the receiver got a new message which is processed and string replaced.

This PR can fix this problem

2021-02-24 09:02 UTC, sualko requested changes
To solve the issue the message should be added after the pipe promise resolves, or we the [chat message ui](https://github.com/jsxc/jsxc/blob/master/src/ui/ChatWindowMessage.ts#L217) should listen for text updates. I would prefer the second approach, because otherwise the user has to wait sometime until the message is shown in the chat area.

2021-02-24 09:02 UTC, sualko commented on src/ui/ChatWindow.ts
> +      this.getTranscript().pushMessage(message);
At this point it is not guaranteed that the pipe has finished (e.g. a plugin could wait for a http request to finish).

2021-02-24 09:20 UTC, sualko commented
@anvyzhang no need to close this pr. It's a good reminder to fix the issue and if you have time you can also force push your fix for that.

2021-02-24 10:07 UTC, anvyzhang commented
Ok, but I think it's better to wait some time(short enouth, otherwise mabe we should find another better way to implement our idea rather than use presend functions), because sync message process may made some splash or refresh on message, which is harmful for endusers.

2021-02-24 10:09 UTC, sualko commented
If you could tell me what you try to do, I maybe can help you.

2021-02-24 10:11 UTC, anvyzhang commented
I made the message more rich formatted, to better display images, links, and even robot message card style. @sualko

2021-12-28 15:42 UTC, sualko commented
> I made the message more rich formatted, to better display images, links, and even robot message card style.

For this you can register a message formatter via `Message.addFormatter`. Since I think that will fix your issue, I close this pr. If not, please provide an example.

2021-12-28 15:42 UTC, closed without merging